### ISSUE TITLE
semgrep not getting detected on MacOS

### ISSUE THREAD

**Issue by gbiagomba** [gand3lf/semgrepper#6]
This is in reference to this comment/issue https://github.com/gand3lf/semgrepper/issues/1#issuecomment-1463711209 

```
It seems that you don't have Semgrep installed!

Please, follow these instructions to install it:
 • Ubuntu, Windows through Windows Subsystem for Linux (WSL), Linux, macOS:
     python3 -m pip install semgrep
 • macOS:
     brew install semgrep
```

I tried the jar file you created and it didnt work

**Comment by gbiagomba** [comment]
@gand3lf I wonder if this will help
```
      if(envs.keySet().contains("__CFBundleIdentifier")){
            //MacOS
            processBuilder.command("/opt/homebrew/bin/semgrep", "--version");
        } else if (os == "Darwin"){
            // MacOS Alternative
            processBuilder.command("/usr/local/bin/semgrep", "--version");
        } else if (os == "Linux"){
            // Linux
            processBuilder.command("/usr/bin/semgrep", "--version");
        } else {
            processBuilder.command("semgrep", "--version");
        }
```

**Comment by gand3lf** [comment]
Hi @gbiagomba, can you provide me the debug messages that you can obtain using the following two versions? https://github.com/gand3lf/semgrepper/issues/1#issuecomment-1463554712

**Comment by gand3lf** [comment]
Hi @gbiagomba, could you try this version? It should work
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11295961/Semgrepper.zip)

**Comment by gand3lf** [comment]
The error should be fixed with the latest version.

**Comment by gbiagomba** [comment]
@gand3lf I will give it a try

**Comment by gbiagomba** [comment]
it worked! what did you do to fix it @gand3lf
