### ISSUE TITLE
another bug

### ISSUE THREAD

**Issue by Miracles666** [gand3lf/semgrepper#8]
i'm try to add a rule for semgrep :It seems that the path is incorrect
![image](https://user-images.githubusercontent.com/40236845/233672382-38b01410-e32d-47e6-99c2-b8ba706a52e0.png)

**Comment by gand3lf** [comment]
This is the command executed by the plugin in this case:
`wsl semgrep --scan-unknown-extensions --config F:\BurpSuiteProv2023.2\xss.yaml ./targetProject`
Could you launch it from the win prompt and tell me what you obtain?

**Comment by Miracles666** [comment]
It seems that the local disk to WSL is mounted in the form of adding  /mnt, like this
![image](https://user-images.githubusercontent.com/40236845/233759329-1b3743db-2a91-43c4-acd6-ebf14ffacfe5.png)

**Comment by Miracles666** [comment]
hi @gand3lf  can you fix it?

**Comment by gand3lf** [comment]
Hi @Miracles666, this version introduce a "/mnt/" and substitute the ":" with "/". Please let me know if it works.
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11301611/Semgrepper.zip)

**Comment by Miracles666** [comment]
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[ERROR] WARNING: unable to find a config; path `/mnt/F/BurpSuiteProv2023.2/semgrep/xss.yaml` does not exist
[ERROR] invalid configuration file found (1 configs were invalid)
 
hi @gand3lf  

This F requires lowercase subtitles
/mnt/f/BurpSuiteProv2023.2/semgrep/xss.yaml

**Comment by gand3lf** [comment]
@Miracles666 this is with the lowercase char:
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11301726/Semgrepper.zip)

**Comment by Miracles666** [comment]
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[ERROR] File not found: C:UsersMiraclesAppDataLocalTemp/SEMDIR_BURP_PLUGIN/MQmPIhWJNh6yUu3I14HcNsOzFomlFRsgY22Egiwg6TQ=
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[ERROR] File not found: C:UsersMiraclesAppDataLocalTemp/SEMDIR_BURP_PLUGIN/h8hpgCMo8nKQ9yG4jRpAEa2kIk5YUioDn0jJK4MF0pQ=

Looks like there's still a problem with the path

**Comment by gand3lf** [comment]
@Miracles666 now? 
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11301773/Semgrepper.zip)

**Comment by Miracles666** [comment]
There's an extra one ahead/
![image](https://user-images.githubusercontent.com/40236845/233813293-5a0027b7-78b7-42eb-a630-d7cc26cb3bd4.png)

[ERROR] File not found: /mnt/java.io.FileNotFoundException/ /mnt/c/Users/Miracles/AppData/Local/Temp/SEMDIR_BURP_PLUGIN/oTu1W2KVFbU+GD01zR7UGmb7Se4Vl8vOv3ivde7YIt0= (绯荤粺鎵句笉鍒版寚瀹氱殑璺緞銆�)

**Comment by gand3lf** [comment]
Unfortunately, without a system where to check my changes it is difficult to patch this problem.
I'm trying this approach:
- if I access to files with FileWriter then I use the path "C:/...."
- if I access to files in wsl then I use the path "/mnt/c/..."

I hope this work: 
[Semgrepper.zip](https://github.com/gand3lf/semgrepper/files/11303231/Semgrepper.zip)

(Today I don't have time to make other changes, I will improve the code tomorrow)

**Comment by Miracles666** [comment]
Fortunately, it successfully ran, but there were garbled codes.
![image](https://user-images.githubusercontent.com/40236845/233829544-39126d53-7072-422d-b9ee-48cf484128ba.png)

This is my burp settings
![image](https://user-images.githubusercontent.com/40236845/233829578-71f34b2b-14e1-4aa9-9618-433bcf9c7f22.png)

**Comment by Miracles666** [comment]
hi @gand3lf can you fix it?

**Comment by gand3lf** [comment]
hi @Miracles666, that is an error related to the error log section. I have modified the code to handle the output of the tool but not the error log area. Since the problem has been solved I close the issue. Thank you for the collaboration!
